name: Website Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy_website]') || contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Configure Git Credientials
        run: |
          git config --global user.email "theguild-bot@users.noreply.github.com"
          git config --global user.name "theguild-bot"
          echo "machine github.com login theguild-bot password ${{secrets.GITHUB_TOKEN}}" > ~/.netrc
      - name: Add origin remote and refetch master
        run: |
          git remote rm origin
          git remote add origin "https://github.com/${{github.repository}}"
          git fetch
          git checkout master
          git reset --hard
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-15-15-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-15-15-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Deploy 🚀
        run: yarn deploy:website
        env:
          GIT_USER: theguild-bot
